### ISSUE TITLE
TypeError: Cannot read property 'i' of undefined

### ISSUE THREAD

**Issue by TJTJliao** [ArtGateOne/ma2apcmini#3]
Hi 
when i using apcmk2, it suddenly cant work, and show type error at below
My ma2 on pc version is 3.9.60.63
Did anyone met this before? and how to solve it?

Thanks alot!

C:\Users\liao2>node ma2apcminimk2.js
Akai APC mini MA2 WING 3

Midi IN
[ 'APC mini mk2', 'MIDIIN2 (APC mini mk2)' ]
Midi OUT
[
  'Microsoft GS Wavetable Synth',
  'APC mini mk2',
  'MIDIOUT2 (APC mini mk2)'
]

Connecting to midi device APC mini mk2
Connecting to grandMA2 ...
WebSocket Client Connected
SERVER READY
LOGIN ...
...LOGGED
SESSION 3
C:\Users\liao2\ma2apcminimk2.js:556
                        if ((obj.itemGroups[0].items[0][i].i.c) != "#000000") {
                                                           ^

TypeError: Cannot read property 'i' of undefined
    at W3CWebSocket.client.onmessage (C:\Users\liao2\ma2apcminimk2.js:556:60)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Users\liao2\node_modules\yaeti\lib\EventTarget.js:107:17)
    at W3CWebSocket.onMessage (C:\Users\liao2\node_modules\websocket\lib\W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (C:\Users\liao2\node_modules\websocket\lib\W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:376:20)
    at WebSocketConnection.processFrame (C:\Users\liao2\node_modules\websocket\lib\WebSocketConnection.js:554:26)
    at C:\Users\liao2\node_modules\websocket\lib\WebSocketConnection.js:323:40
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

C:\Users\liao2>

**Comment by ArtGateOne** [comment]
Is this happening right after startup? If so, does it occur in Wing 2 or Wing 1 mode on this SHOW?

Do you have an executor expanded to 2 fields or more?

**Comment by ArtGateOne** [comment]
I've just tested it on version 3.9.60.50, and everything is working correctly. I also tested it on the latest version, 3.9.60.65, and it's working fine as well.

Does this issue also occur on the new show? Please let me know!

**Comment by TJTJliao** [comment]
Thanks to your comment, just because I move a 2 field executor to the apcmini's fader position, remove that all back to normal.
Thanks a million!
